import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Travel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="h-screen bg-[#F8F9FF]">
        {children}
        </main>
        </body>
    </html>
  );
}
